openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/auth/login:
    post:
      summary: ''
      operationId: postApiAuthLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: wglover@example.com
                password:
                  type: string
                  description: ''
                  example: voluptas
                device_name:
                  type: string
                  description: ''
                  example: maiores
              required:
                - email
                - password
      security: []
  /api/auth/logout:
    post:
      summary: ''
      operationId: postApiAuthLogout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                token_id:
                  type: string
                  description: ''
                  example: asperiores
      security: []
  /api/auth/logout-all:
    post:
      summary: ''
      operationId: postApiAuthLogoutAll
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/auth/profile:
    get:
      summary: ''
      operationId: getApiAuthProfile
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      operationId: putApiAuthProfile
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: eos
      security: []
  /api/me/houses:
    get:
      summary: ''
      operationId: getApiMeHouses
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: ''
      operationId: postApiMeHouses
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: cbpyvncjutjslsxoxsta
                address:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: hphzececvznnfdkcoqvjd
                description:
                  type: string
                  description: ''
                  example: 'Est nulla rerum quibusdam illum perspiciatis velit laboriosam.'
              required:
                - name
                - address
      security: []
  '/api/me/houses/{id}':
    get:
      summary: ''
      operationId: getApiMeHousesId
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      operationId: putApiMeHousesId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: vbatpdrzrnxqjdawt
                address:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: oesqvblbmysbaauimjlsepswm
                description:
                  type: string
                  description: ''
                  example: 'Libero tempore dolore facere sit.'
      security: []
    delete:
      summary: ''
      operationId: deleteApiMeHousesId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the house.'
        example: 4
        required: true
        schema:
          type: integer
  '/api/me/houses/{house_id}/bills':
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: house_id
        description: 'The ID of the house.'
        example: 5
        required: true
        schema:
          type: integer
  '/api/me/houses/{house_id}/bills/{id}':
    get:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: house_id
        description: 'The ID of the house.'
        example: 7
        required: true
        schema:
          type: integer
      -
        in: path
        name: id
        description: 'The ID of the bill.'
        example: laudantium
        required: true
        schema:
          type: string
  '/api/me/bills/{bill_id}/attachments':
    get:
      summary: ''
      operationId: getApiMeBillsBill_idAttachments
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: ''
      operationId: postApiMeBillsBill_idAttachments
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                bill_id:
                  type: string
                  description: ''
                  example: iusto
                file:
                  type: string
                  format: binary
                  description: 'Must be a file.'
              required:
                - bill_id
                - file
      security: []
    parameters:
      -
        in: path
        name: bill_id
        description: 'The ID of the bill.'
        example: 2
        required: true
        schema:
          type: integer
  '/api/me/attachments/{id}':
    get:
      summary: ''
      operationId: getApiMeAttachmentsId
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      operationId: putApiMeAttachmentsId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: 'Must be a file.'
      security: []
    delete:
      summary: ''
      operationId: deleteApiMeAttachmentsId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the attachment.'
        example: 12
        required: true
        schema:
          type: integer
tags:
  -
    name: Endpoints
    description: ''
